packages:
  - firefox/
  - chrome/
catalog:
  adm-zip: ^0.5.16
  copy-webpack-plugin: ^12.0.2
  css-loader: ^7.1.2
  dompurify: ^3.2.3
  dotenv-webpack: ^8.1.0
  file-loader: ^6.2.0
  mini-css-extract-plugin: ^2.9.2
  prettier: ^3.4.2
  webpack: ^5.97.1
  webpack-cli: ^6.0.1
  webpack-merge: ^6.0.1
